### ISSUE TITLE
Undoing causes Following files have changes that cannot be undone: error

### ISSUE THREAD

**Issue by villesau** [reasonml-editor/reasonml-idea-plugin#192]
plugin version: 0.81

### Description

The project has been made with following command: `bsb -init my-new-project -theme basic-reason`

Repro:
1. save file with changes
2. file reformats
3. cmd + z (undo)
4. popup saying `Following files have changes that cannot be undone:` pops up.
<img width="428" alt="Screenshot 2019-11-09 at 19 52 58" src="https://user-images.githubusercontent.com/2647016/68532814-a336aa80-032a-11ea-85d5-d4d97333a4bb.png">

This is rather annoying since often times you really would like to undo something.

**Comment by giraud** [comment]
should be fixed in 0.84

**Comment by villesau** [comment]
@giraud this is still happening with this version: 0.84-2019.3 and following ide version:

IntelliJ IDEA 2019.3.1 (Ultimate Edition)
Build #IU-193.5662.31, built on December 10, 2019
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: Dart, Karma, com.intellij.lang.jsgraphql, com.intellij.plugins.html.instantEditing, com.jetbrains.php, com.jetbrains.plugins.ini4idea, io.flutter, org.jetbrains.plugins.ruby, net.ashald.envfile, net.seesharpsoft.intellij.plugins.csv, reasonml

**Comment by maximenathan** [comment]
I have the same problem webstorm 2020.2

**Comment by giraud** [comment]
2020.2 is not supported, you have an old version of the plugin

**Comment by Smolyan91** [comment]
> I have the same problem webstorm 2020.2

@maximenathan , Do you solve this problem ? I have same problem

**Comment by LiucCheng** [comment]
怎么解决，我的也出现了，webstrom怎么感觉越来越多问题？

**Comment by jovancacvetkovic** [comment]
IntelliJ IDEA 2022.3.1 (Ultimate Edition) pops-up all the time, its just one change and it says it cant be undone. No logs what so ever.

**Comment by lexizz** [comment]
@giraud I have same problem
```
GoLand 2022.3.1
Build #GO-223.8214.59, built on December 21, 2022
Runtime version: 17.0.5+1-b653.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.1.12-1-manjaro
GC: G1 Young Generation, G1 Old Generation
Memory: 1970M
Cores: 8
Registry:
    editor.focus.mode.color.light=6b727d
    ide.editor.tab.selection.animation=true
    suggest.all.run.configurations.from.context=true
    ide.completion.variant.limit=500
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=6b727d

Non-Bundled Plugins:
    com.mallowigi (85.1.0)
    com.chrisrm.idea.MaterialThemeUI (8.4.1)
    com.ypwang.plugin.go-linter (1.6.3)

Current Desktop: KDE
```
And
```
PhpStorm 2022.3.1
Build #PS-223.8214.64, built on December 22, 2022
Runtime version: 17.0.5+1-b653.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.1.12-1-manjaro
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    editor.focus.mode.color.light=6b727d
    ide.editor.tab.selection.animation=true
    debugger.watches.in.variables=false
    run.processes.with.pty=TRUE
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=6b727d

Non-Bundled Plugins:
    com.kalessil.phpStorm.phpInspectionsEA (4.0.7.1)
    com.chrisrm.idea.MaterialThemeUI (8.4.1)
    com.yii2support (0.10.58.37)
    ru.adelf.idea.dotenv (2022.3)
    com.mallowigi (85.1.0)

Current Desktop: KDE
```

**Comment by giraud** [comment]
which version of plugin ?
do you have an external process that update files in parallel ?

**Comment by giraud** [comment]
can you, please, test if plugin 0.111-beta01-2022.3 fixes your problem ?
you should find it here: https://plugins.jetbrains.com/plugin/9440-reasonml/versions/beta

**Comment by somesh-scoville** [comment]
> can you, please, test if plugin 0.111-beta01-2022.3 fixes your problem ? you should find it here: https://plugins.jetbrains.com/plugin/9440-reasonml/versions/beta

Is this plugin available for mac os? Thank you.

**Comment by giraud** [comment]
This is an old beta version. Use latest version
